target-version = "py311"
line-length = 100
src = ["src", "tests"]

[lint]
select = ["E", "F", "I", "W", "UP", "B", "SIM"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["E501"]
"src/addsong/cli.py" = ["SIM102"]