"""Shell completion script generation for `addsong --print-completion`.

One source of truth: the subcommand list, option flags, and value-taking
options are declared once here; `--print-completion bash|zsh|fish` emits the
matching completion script so users don't hand-edit shell files. The CLI
flags are kept in sync with `cli._build_parser` / `_help_text`.
"""

from __future__ import annotations

from addsong.constants import AUDIO_FORMATS

# Subcommands the CLI peeks before flag parsing (cli._SUBCOMMANDS), with the
# one-line descriptions shown by shell completion menus.
_SUBCOMMANDS: tuple[tuple[str, str], ...] = (
    ("subscribe", "Remember a playlist URL for repeat syncs"),
    ("unsubscribe", "Forget a subscribed playlist URL"),
    ("list", "Show subscribed playlists"),
    ("sync", "Import new tracks from every subscription"),
    ("forget", "Forget every imported track (reset dedup)"),
)

# (long, short-or-None, takes_value, help). Order matches --help so the
# generated completion stays in sync with what the parser accepts.
_OPTIONS: tuple[tuple[str, str | None, bool, str], ...] = (
    ("--playlist", None, False, "Treat the URL as a playlist"),
    ("--from", None, True, "Read URLs from FILE (- for stdin)"),
    ("--results", None, True, "Free-text YouTube search; import top N (1-50)"),
    ("--yes", "-y", False, "Don't prompt; accept metadata"),
    ("--review", None, False, "Always prompt to review metadata"),
    ("--reimport", None, False, "Import even if already imported"),
    ("--dry-run", "-n", False, "Resolve/show metadata; import nothing"),
    ("--quiet", "-q", False, "Suppress info banners and status"),
    ("--verbose", "-v", False, "Surface yt-dlp/ffmpeg stderr"),
    ("--no-progress", None, False, "Use spinner instead of real bar"),
    ("--format", None, True, f"Audio format: {' '.join(AUDIO_FORMATS)}"),
    ("--quality", None, True, "Audio quality 0-10, 0=best"),
    ("--notify", None, False, "Desktop notification per imported track"),
    ("--no-color", None, False, "Disable colored output"),
    ("--help", "-h", False, "Show help and exit"),
    ("--version", None, False, "Print version and exit"),
    ("--print-completion", None, True, "Print shell completion and exit"),
)

_SHELLS = ("bash", "zsh", "fish")


def shells() -> tuple[str, ...]:
    return _SHELLS


def _all_flag_tokens() -> tuple[str, ...]:
    toks: list[str] = []
    for long, short, _takes, _help in _OPTIONS:
        toks.append(long)
        if short:
            toks.append(short)
    return tuple(toks)


def render(shell: str) -> str:
    if shell == "bash":
        return _bash()
    if shell == "zsh":
        return _zsh()
    if shell == "fish":
        return _fish()
    raise ValueError(f"unknown shell: {shell!r} (want one of: {' '.join(_SHELLS)})")


def _bash() -> str:
    opts = " ".join(_all_flag_tokens())
    subs = " ".join(name for name, _desc in _SUBCOMMANDS)
    fmt = " ".join(AUDIO_FORMATS)
    return (
        "# bash completion for addsong\n"
        "# Generated by `addsong --print-completion bash`.\n"
        "# Install by sourcing from your bashrc, or drop into a bash completion dir:\n"
        "#     source <(addsong --print-completion bash)\n"
        "\n"
        "_addsong() {\n"
        '    local cur="${COMP_WORDS[COMP_CWORD]}"\n'
        '    local prev="${COMP_WORDS[COMP_CWORD-1]}"\n'
        "\n"
        f'    local subs="{subs}"\n'
        f'    local opts="{opts}"\n'
        "\n"
        "    case \"$prev\" in\n"
        f'        --format) COMPREPLY=( $(compgen -W "{fmt}" -- "$cur") ); return ;;\n'
        "        --quality) COMPREPLY=( $(compgen -W \"0 1 2 3 4 5 6 7 8 9 10\""
        " -- \"$cur\") ); return ;;\n"
        '        --from)    COMPREPLY=( $(compgen -f -- "$cur") ); return ;;\n'
        "        --print-completion) COMPREPLY=( $(compgen -W \""
        + " ".join(_SHELLS) + "\" -- \"$cur\") ); return ;;\n"
        "        --results) return ;;\n"
        "    esac\n"
        "\n"
        '    if [[ "$COMP_CWORD" -eq 1 ]]; then\n'
        '        COMPREPLY=( $(compgen -W "$subs $opts" -- "$cur") )\n'
        '    elif [[ "$cur" == -* ]]; then\n'
        '        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )\n'
        "    fi\n"
        "}\n"
        "complete -F _addsong addsong\n"
    )


def _zsh() -> str:
    subs_lines = "\n".join(
        "    '" + name + ":" + desc.replace("'", "''") + "'"
        for name, desc in _SUBCOMMANDS
    )
    fmt = " ".join(AUDIO_FORMATS)
    shells = " ".join(_SHELLS)
    args_lines = []
    for long, short, takes, help in _OPTIONS:
        if short is not None:
            # Combine short+long using the {-s,--long} zsh brace form.
            spec = "'(-" + short[1] + " " + long + ")'{-" + short[1] + "," + long + "}"
        else:
            spec = "'" + long + "'"
        desc = help.replace("'", "''")
        typer = ""
        if takes and long == "--format":
            typer = ":{" + fmt + "}"
        elif takes and long == "--quality":
            typer = ":{0 1 2 3 4 5 6 7 8 9 10}"
        elif takes and long == "--from":
            typer = ":file:_files"
        elif takes and long == "--print-completion":
            typer = ":{" + shells + "}"
        elif takes:
            typer = ":"
        args_lines.append("    " + spec + "'[" + desc + "]'" + typer)
    args_block = " \\\n".join(args_lines)
    return (
        "#compdef addsong\n"
        "# zsh completion for addsong.\n"
        "# Generated by `addsong --print-completion zsh`.\n"
        "# Install: put this file (named `_addsong`) on your $fpath, then\n"
        "#     fpath=(~/.zsh/completions $fpath); autoload -U compinit && compinit\n"
        "\n"
        "_addsong() {\n"
        "    local -a subs\n"
        "    subs=(\n"
        f"{subs_lines}\n"
        "    )\n"
        "    _arguments -s -C \\\n"
        f"{args_block} \\\n"
        "        '1: :->cmd' \\\n"
        "        '*::arg:->args'\n"
        "\n"
        "    case $state in\n"
        "        cmd) _describe -t commands 'addsong command' subs ;;\n"
        "    esac\n"
        "}\n"
        "_addsong \"$@\"\n"
    )


def _fish() -> str:
    fmt = " ".join(AUDIO_FORMATS)
    shells = " ".join(_SHELLS)
    lines = [
        "# fish completion for addsong.",
        "# Generated by `addsong --print-completion fish`.",
        "# Install: add to your fish completions dir (e.g. ~/.config/fish/completions/):",
        "#     addsong --print-completion fish > ~/.config/fish/completions/addsong.fish",
        "",
    ]
    for name, desc in _SUBCOMMANDS:
        desc_ = desc.replace("'", "\\'")
        lines.append(
            "complete -c addsong -n '__fish_use_subcommand' -a '" + name + "' "
            "-d '" + desc_ + "'"
        )
    for long, short, takes, help in _OPTIONS:
        help_ = help.replace("'", "\\'")
        shorttoken = short[1:] if short is not None else ""
        shortopt = ("-s " + shorttoken + " ") if shorttoken else ""
        base = "complete -c addsong -l " + long[2:] + " " + shortopt
        if takes:
            if long == "--from":
                lines.append(base + "-r -f -a '(__fish_complete_path)' -d '" + help_ + "'")
            elif long == "--format":
                lines.append(base + "-r -f -a '" + fmt + "' -d '" + help_ + "'")
            elif long == "--quality":
                lines.append(base + "-r -f -a '0 1 2 3 4 5 6 7 8 9 10' -d '" + help_ + "'")
            elif long == "--print-completion":
                lines.append(base + "-r -f -a '" + shells + "' -d '" + help_ + "'")
            else:
                lines.append(base + "-r -d '" + help_ + "'")
        else:
            lines.append(base + "-d '" + help_ + "'")
    return "\n".join(lines) + "\n"
